### ISSUE TITLE
Laravel 7 Compatibility

### ISSUE THREAD

**Issue by ejntaylor** [Juhlinus/Inertia-Vue#5]
On install I get:

Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: laravel/framework[v7.4.0, 5.8.x-dev].
    - Can only install one of: laravel/framework[5.8.x-dev, v7.4.0].
    - Can only install one of: laravel/framework[5.8.x-dev, v7.4.0].
    - juhlinus/inertia-vue 0.0.7 requires laravel/framework ^5.8 -> satisfiable by laravel/framework[5.8.x-dev].
    - Installation request for juhlinus/inertia-vue ^0.0.7 -> satisfiable by juhlinus/inertia-vue[0.0.7].
    - Installation request for laravel/framework (locked at v7.4.0, required as ^7.0) -> satisfiable by laravel/framework[v7.4.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by Juhlinus** [comment]
Fixed in [0.0.8](https://github.com/Juhlinus/Inertia-Vue/releases/tag/0.0.8).
